### ISSUE TITLE
How do we directly connect to the device without selecting device from popup list?

### ISSUE THREAD

**Issue by narada85** [manekinekko/angular-web-bluetooth#20] opened 2017-08-24 09:22 UTC

**Comment by beaufortfrancois** [comment] 2017-08-24 09:35
You can't for now as the Permissions API has not been integrated to the Web Bluetooth API.
See https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md#gatt-communication-api and https://webbluetoothcg.github.io/web-bluetooth/#permission-api-integration

**Comment by narada85** [comment] 2017-08-24 09:57
@beaufortfrancois device UUID and name wont help?

**Comment by narada85** [comment] 2017-08-24 10:00
Since electron doesn't have popup available to show device list, somehow i need to connect to device and read the data, Do you have any thoughts on this matter? Tx!

**Comment by beaufortfrancois** [comment] 2017-08-24 12:29
I believe* you should be able to see the popup according to https://github.com/aalhaimi/electron-web-bluetooth

**Comment by narada85** [comment] 2017-08-24 13:00
@beaufortfrancois i'm doing angular2 web app and going to convert it to electron. So this proposed plugin doesn't support, since angular2 supports only **typescript**.

this ' https://github.com/aalhaimi/electron-web-bluetooth' plugin doesn't show popup, but it takes around 1 min to send the response.

**Comment by manekinekko** [comment] 2017-08-24 21:46
> @beaufortfrancois i'm doing angular2 web app and going to convert it to electron. So this proposed plugin doesn't support, since angular2 supports only typescript.

@narada85 what do you mean by that? **typescript** is just javascript. What are you trying to accomplish?

**Comment by narada85** [comment] 2017-08-25 07:19
@manekinekko i need to convert this ' https://github.com/aalhaimi/electron-web-bluetooth' code to ng2, but how do i do that without typings?

**Comment by manekinekko** [comment] 2017-08-25 10:55
The electron app is just a shell app. You don't have to convert it to typescript. You can for instance, use this project [starter](https://github.com/manekinekko/angular-web-bluetooth-starter) and launch it with the electron app by calling the URL like in this line: https://github.com/aalhaimi/electron-web-bluetooth/blob/master/main.js#L21

**Comment by narada85** [comment] 2017-08-25 11:48
@manekinekko It worked, tx!, it didn't show up device popup list. but shows battery level after 1min.

**Comment by manekinekko** [comment] 2017-08-25 23:31
@beaufortfrancois do you know what could cause that delay? Does it depends on the device specs?

**Comment by beaufortfrancois** [comment] 2017-08-28 07:28
@narada85 Did you read battery level or did you wait for a BLE GATT notification?

**Comment by narada85** [comment] 2017-08-28 07:33
@beaufortfrancois, 
i did read the battery level.

**Comment by beaufortfrancois** [comment] 2017-08-28 07:37
Can you share code and logs with timestamps?
1 minute is a long time ;)

**Comment by beaufortfrancois** [comment] 2017-08-28 07:37
Can you reproduce with https://googlechrome.github.io/samples/web-bluetooth/battery-level.html?

**Comment by narada85** [comment] 2017-08-28 07:58
Here is the output:
https://drive.google.com/file/d/0B-qW8Onx1jDfNkUta2l2U0t3SXc/view?usp=sharing

**Comment by narada85** [comment] 2017-08-28 08:00
@beaufortfrancois
 1. what are the functions that i can use to check device status(like 'connected' 'disconnected')
 2. what are the functions that i can use to check bluetooth status('turn-on and turn-off').
Tx!

**Comment by beaufortfrancois** [comment] 2017-08-28 08:09
1. In vanilla JS, you can use `myBluetoothDevice.gatt.connected`. See https://googlechrome.github.io/samples/web-bluetooth/device-info.html and https://googlechrome.github.io/samples/web-bluetooth/device-disconnect.html
2. You can't for now sadly. In the future, we might have something like https://webbluetoothcg.github.io/web-bluetooth/#availability

Can you share timestamps when device is actually connected?

**Comment by narada85** [comment] 2017-08-28 09:09
@beaufortfrancois pls mention line numbers on following file that you want to put logs. Then i will send you a output.

https://github.com/manekinekko/angular-web-bluetooth-starter/blob/master/src/app/battery-level.service.ts

**Comment by beaufortfrancois** [comment] 2017-08-28 11:43
https://github.com/manekinekko/angular-web-bluetooth-starter/blob/master/src/app/battery-level.service.ts#L37
https://github.com/manekinekko/angular-web-bluetooth-starter/blob/master/src/app/battery-level.service.ts#L46
https://github.com/manekinekko/angular-web-bluetooth-starter/blob/master/src/app/battery-level.service.ts#L49
https://github.com/manekinekko/angular-web-bluetooth-starter/blob/master/src/app/battery-level.service.ts#L52

**Comment by sai-kyaw** [comment] 2017-09-25 17:16
FYI. Delay on electron is due to their bluetooth_chooser implementation. Basically, they scan the devices and only choose the device once the scan timeout reach. [Electron BT Chooser](https://github.com/electron/electron/blob/master/atom/browser/lib/bluetooth_chooser.cc)

**Comment by manekinekko** [comment] 2017-12-21 23:41
I'm closing this issue. Please reopen if needed.

**Closed by manekinekko** 2017-12-21 23:41 UTC
Labels: question
