### ISSUE TITLE
Unsupported device error

### ISSUE THREAD

**Issue by CelebratedPooper** [manekinekko/angular-web-bluetooth#28] opened 2018-02-08 16:11 UTC
I wrote a small demo program to test this lib. I mainly used the code from the starter project for my service and my component.

And I setup a GATT-server with a battery service and a battery level characteristic on my phone.

When I call _getBatteryLevel()_ I can choose my device but I can not retrieve the data. I get the debug message _ERROR Error: Uncaught (in promise): Unsupported device._ followed by _ERROR TypeError: Cannot read property 'getPrimaryService' of undefined_.

I am not sure if this is a general web bluetooth problem or a problem with this library.

**Comment by manekinekko** [comment] 2018-02-08 17:22
I guess the error message is clear: `Unsupported device.` This means that the device is not supported by your browser. Can you give more details about the app you used to create the GATT-server?

**Comment by CelebratedPooper** [comment] 2018-02-08 18:44
I used _nRF Connect_. Is there a list with supported devices or with the requierments for the device?

**Comment by manekinekko** [comment] 2018-02-11 11:38
The only requirement is It should be any "smart bluetooth (or BLE)" enabled device that exposes (in your case) the battery service UUID.

**Comment by CelebratedPooper** [comment] 2018-02-12 08:54
The device I used as GATT-server was a _Pixel 2_.

I was able to access the battery service provided by this server via a _Nexus 5_. To read the data I used _nRF Connect_ on the _Nexus_.

**Comment by manekinekko** [comment] 2018-02-14 20:58
I will need to reproduce this in order to understand what's going on. Could you share the repro steps?

**Comment by CelebratedPooper** [comment] 2018-02-16 08:28
This is my service:

```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { BluetoothCore } from '@manekinekko/angular-web-bluetooth';

@Injectable()
export class BtService {
  static GATT_CHARACTERISTIC_BATTERY_LEVEL = 'battery_level';
  static GATT_PRIMARY_SERVICE = 'battery_service';

  constructor(public ble: BluetoothCore) {}

  getFakeValue() {
    this.ble.fakeNext();
  }

  getDevice() {
    return this.ble.getDevice$();
  }

  streamValues() {
    return this.ble.streamValues$().map((value: DataView) => value.getUint8(0));
  }

  /**
   * Get Battery Level GATT Characteristic value.
   * This logic is specific to this service, this is why we can't abstract it elsewhere.
   * The developer is free to provide any service, and characteristics she wants.
   *
   * @return {Observable<Number>} Emites the value of the requested service read from the device
   */
  getBatteryLevel() {
    console.log('Getting Battery Service...');

    try {
      return this.ble
        .discover$({
          acceptAllDevices: true,
          optionalServices: [BtService.GATT_PRIMARY_SERVICE]
        })
        .mergeMap((gatt: BluetoothRemoteGATTServer) => {
          return this.ble.getPrimaryService$(
            gatt,
            BtService.GATT_PRIMARY_SERVICE
          );
        })
        .mergeMap((primaryService: BluetoothRemoteGATTService) => {
          return this.ble.getCharacteristic$(
            primaryService,
            BtService.GATT_CHARACTERISTIC_BATTERY_LEVEL
          );
        })
        .mergeMap((characteristic: BluetoothRemoteGATTCharacteristic) => {
          return this.ble.readValue$(characteristic);
        })
        .map((value: DataView) => value.getUint8(0));
    } catch (e) {
      console.error('Oops! can not read value from %s');
    }
  }
}
```

And this is my component:

```
import { Component, OnInit, NgZone } from '@angular/core';

import { BtService } from '../bt.service';
import { BluetoothCore } from '@manekinekko/angular-web-bluetooth';

@Component({
  selector: 'app-bt',
  templateUrl: './bt.component.html',
  styleUrls: ['./bt.component.css'],
  providers: [BtService]
})
export class BtComponent implements OnInit {

  batteryLevel: string = '--';
  device: any = {};

  constructor(
    public _zone: NgZone,
    public _btService: BtService
  ) {}

  ngOnInit() {
    this.getDeviceStatus();
    this.streamValues();
  }

  streamValues() {
    this._btService.streamValues().subscribe(this.showBatteryLevel.bind(this));
  }

  getDeviceStatus() {
    this._btService.getDevice().subscribe(
      (device) => {

        if (device) {
          this.device = device;
        }
        else 
        {
          // device not connected or disconnected
          this.device = null;
          this.batteryLevel = '--';
        }
      }
    );
  }

  getFakeValue() {
    this._btService.getFakeValue();
  }

  getBatteryLevel() {
    return this._btService.getBatteryLevel().subscribe(this.showBatteryLevel.bind(this));
  }

  showBatteryLevel(value: number) {

    // force change detection
    this._zone.run( () =>  {
      console.log('Reading battery level %d', value);
      this.batteryLevel = '' + value;
    });
}

}
```
The html-file for the component only contains one line:
`<a href="#" (click)="getBatteryLevel()">Get Battery Level ({{batteryLevel || 'N/A'}}%)</a>`

As GATT-Server I use a _Pixel 2_ with _nRF Connect_. I created a default battery service with a battery level characteristic.

When I click the link in the component I can choose my device from a list. After that nothing happens in the app but the console prints out some errors. If it is somehow helpful I can post the console-log.

Thanks for your help!

**Comment by manekinekko** [comment] 2018-03-29 22:12
Hi @CelebratedPooper I couldn't reproduce your error. As you can see from the screenshot below, everything is working as expected. Please feel free to close this issue and open another one if needed.


![image](https://user-images.githubusercontent.com/1699357/38116100-f0544e64-33ae-11e8-9a40-59a752790dab.png)

**Closed** 2018-03-29 22:32 UTC
